name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/
    - assets/page-1/images/image-3-bg.png
    - assets/page-1/images/image-2.png
    - assets/page-1/images/image-2-jMz.png
    - assets/page-1/images/image-2-a4x.png
    - assets/page-1/images/image-2-Yja.png
    - assets/page-1/images/image-2-jZA.png
    - assets/page-1/images/image-2-1iY.png
    - assets/page-1/images/image-2-jpt.png
    - assets/page-1/images/image-2-bcU.png
    - assets/page-1/images/image-2-cPr.png
    - assets/page-1/images/image-2-Rgc.png
    - assets/page-1/images/image-2-S9n.png
    - assets/page-1/images/image-2-jN8.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/vector-1ap.png
    - assets/page-1/images/vector-fHJ.png
    - assets/page-1/images/vector-dTe.png
    - assets/page-1/images/vector-Lu6.png
    - assets/page-1/images/vector-t5n.png
    - assets/page-1/images/vector-DjW.png
    - assets/page-1/images/vector-mCc.png
    - assets/page-1/images/vector-TNp.png
    - assets/page-1/images/vector-unp.png
    - assets/page-1/images/vector-QMN.png
    - assets/page-1/images/vector-tZN.png
    - assets/page-1/images/vector-aiL.png
    - assets/page-1/images/vector-uqi.png
    - assets/page-1/images/vector-aWc.png
    - assets/page-1/images/vector-WTA.png
    - assets/page-1/images/vector-43z.png
    - assets/page-1/images/vector-9di.png
    - assets/page-1/images/vector-8rL.png
    - assets/page-1/images/vector-2hE.png
    - assets/page-1/images/vector-2Fi.png
    - assets/page-1/images/vector-mwN.png
    - assets/page-1/images/vector-cPa.png
    - assets/page-1/images/vector-Qak.png
    - assets/page-1/images/vector-N4G.png
    - assets/page-1/images/vector-y2g.png
    - assets/page-1/images/vector-TBN.png
    - assets/page-1/images/vector-ZQ4.png
    - assets/page-1/images/vector-M76.png
    - assets/page-1/images/vector-kEU.png
    - assets/page-1/images/vector-3AG.png
    - assets/page-1/images/vector-trC.png
    - assets/page-1/images/vector-oD2.png
    - assets/page-1/images/vector-nTS.png
    - assets/page-1/images/vector-ZQC.png
    - assets/page-1/images/image-2-CXa.png
    - assets/page-1/images/vector-ndW.png
    - assets/page-1/images/vector-5PN.png
    - assets/page-1/images/vector-qH2.png
    - assets/page-1/images/vector-nxG.png
    - assets/page-1/images/vector-uBe.png
    - assets/page-1/images/vector-d2G.png
    - assets/page-1/images/vector-Lek.png
    - assets/page-1/images/vector-sVa.png
    - assets/page-1/images/vector-85N.png
    - assets/page-1/images/vector-8Dn.png
    - assets/page-1/images/vector-u3W.png
    - assets/page-1/images/vector-ycC.png
    - assets/page-1/images/vector-45n.png
    - assets/page-1/images/vector-9yi.png
    - assets/page-1/images/vector-K68.png
    - assets/page-1/images/vector-QhE.png
    - assets/page-1/images/vector-MEG.png
    - assets/page-1/images/vector-SoS.png
    - assets/page-1/images/vector-tzL.png
    - assets/page-1/images/vector-oA8.png
    - assets/page-1/images/vector-krc.png
    - assets/page-1/images/vector-xzc.png
    - assets/page-1/images/vector-Ms6.png
    - assets/page-1/images/vector-azk.png
    - assets/page-1/images/vector-iTz.png
    - assets/page-1/images/vector-qBE.png
    - assets/page-1/images/vector-tYp.png
    - assets/page-1/images/vector-VEQ.png
    - assets/page-1/images/vector-VQc.png
    - assets/page-1/images/vector-ktG.png
    - assets/page-1/images/vector-9fn.png
    - assets/page-1/images/vector-paL.png
    - assets/page-1/images/vector-UBa.png
    - assets/page-1/images/vector-hiY.png
    - assets/page-1/images/vector-uz8.png
    - assets/page-1/images/vector-UqW.png
    - assets/page-1/images/vector-fNp.png
    - assets/page-1/images/vector-v8x.png
    - assets/page-1/images/vector-wBn.png
    - assets/page-1/images/vector-Xyr.png
    - assets/page-1/images/vector-Wwi.png
    - assets/page-1/images/vector-yWQ.png
    - assets/page-1/images/vector-dZS.png
    - assets/page-1/images/group-2.png
    - assets/page-1/images/vector-XRJ.png
    - assets/page-1/images/vector-Tkc.png
    - assets/page-1/images/vector-ZUC.png
    - assets/page-1/images/vector-Q7z.png
    - assets/page-1/images/vector-22k.png
    - assets/page-1/images/image-4-bg.png
    - assets/page-1/images/vector-u8U.png
    - assets/page-1/images/vector-YTa.png
    - assets/page-1/images/vector-ro2.png
    - assets/page-1/images/vector-gL8.png
    - assets/page-1/images/image-2-hcU.png
    - assets/page-1/images/vector-m7n.png
    - assets/page-1/images/vector-NnU.png
    - assets/page-1/images/group-2-YRE.png
    - assets/page-1/images/image-2-pSC.png
    - assets/page-1/images/vector-zUx.png
    - assets/page-1/images/image-2-6tY.png
    - assets/page-1/images/vector-xCY.png
    - assets/page-1/images/image-2-hXE.png
    - assets/page-1/images/vector-NTz.png
    - assets/page-1/images/vector-UZe.png
    - assets/page-1/images/image-2-pPi.png
    - assets/page-1/images/group-28.png
    - assets/page-1/images/image-1.png
    - assets/page-1/images/image-3-bg-4Xa.png
    - assets/page-1/images/vector-KRr.png
    - assets/page-1/images/vector-4uE.png
    - assets/page-1/images/vector-w1A.png
    - assets/page-1/images/image-2-DjN.png
    - assets/page-1/images/image-2-Bw6.png
    - assets/page-1/images/vector-3yJ.png
    - assets/page-1/images/vector-bhJ.png
    - assets/page-1/images/vector-xnk.png
    - assets/page-1/images/vector-qiY.png
    - assets/page-1/images/vector-U3J.png
    - assets/page-1/images/vector-SPS.png
    - assets/page-1/images/vector-QbA.png
    - assets/page-1/images/vector-yPN.png
    - assets/page-1/images/vector-UrU.png
    - assets/page-1/images/vector-S2c.png
    - assets/page-1/images/vector-CGg.png
    - assets/page-1/images/image-2-doE.png
    - assets/page-1/images/vector-oBv.png
    - assets/page-1/images/vector-Mz8.png
    - assets/page-1/images/image-2-6qE.png
    - assets/page-1/images/vector-Tfn.png
    - assets/page-1/images/vector-PyA.png
    - assets/page-1/images/vector-kHv.png
    - assets/page-1/images/polygon-1.png
    - assets/page-1/images/vector-pyn.png
    - assets/page-1/images/image-2-bg.png
    - assets/page-1/images/vector-NdE.png
    - assets/page-1/images/group-2-XwN.png
    - assets/page-1/images/vector-noi.png
    - assets/page-1/images/vector-azU.png
    - assets/page-1/images/vector-91z.png
    - assets/page-1/images/vector-wZz.png
    - assets/page-1/images/vector-dBv.png
    - assets/page-1/images/vector-Lc8.png
    - assets/page-1/images/vector-LEk.png
    - assets/page-1/images/vector-PNg.png
    - assets/page-1/images/vector-wf6.png
    - assets/page-1/images/image-1-7Jg.png
    - assets/page-1/images/vector-UQ8.png
    - assets/page-1/images/vector-G8x.png
    - assets/page-1/images/vector-jc4.png
    - assets/page-1/images/image-2-DLC.png
    - assets/page-1/images/vector-ZuA.png
    - assets/page-1/images/vector-Vrg.png
    - assets/page-1/images/vector-o9A.png
    - assets/page-1/images/vector-iBS.png
    - assets/page-1/images/vector-2C8.png
    - assets/page-1/images/vector-7Da.png
    - assets/page-1/images/group-2-vV6.png
    - assets/page-1/images/vector-STS.png
    - assets/page-1/images/vector-9ck.png
    - assets/page-1/images/vector-PbN.png
    - assets/page-1/images/vector-tkx.png
    - assets/page-1/images/vector-od2.png
    - assets/page-1/images/image-2-atY.png
    - assets/page-1/images/vector-rTz.png
    - assets/page-1/images/image-3.png
    - assets/page-1/images/vector-sN8.png
    - assets/page-1/images/vector-trC-Ufz.png
    - assets/page-1/images/vector-8LG.png
    - assets/page-1/images/vector-G1n.png
    - assets/page-1/images/vector-tE4.png
    - assets/page-1/images/vector-URW.png
    - assets/page-1/images/image-2-4sS.png
    - assets/page-1/images/vector-a72.png
    - assets/page-1/images/vector-6tG.png
    - assets/page-1/images/vector-LKJ.png
    - assets/page-1/images/vector-Ei4.png
    - assets/page-1/images/vector-2Gg.png
    - assets/page-1/images/vector-ahE.png
    - assets/page-1/images/vector-hU4.png
    - assets/page-1/images/vector-vsA.png
    - assets/page-1/images/vector-LKa.png
    - assets/page-1/images/vector-nNC.png
    - assets/page-1/images/image-2-7Qc.png
    - assets/page-1/images/image-2-haQ.png
    - assets/page-1/images/image-2-Jfr.png
    - assets/page-1/images/vector-V7E.png
    - assets/page-1/images/vector-gbr.png
    - assets/page-1/images/vector-MQ4.png
    - assets/page-1/images/vector-g9N.png
    - assets/page-1/images/image-2-J7i.png
    - assets/page-1/images/rectangle-3-bg.png
    - assets/page-1/images/vector-jzx.png
    - assets/page-1/images/vector-quS.png
    - assets/page-1/images/vector-usE.png
    - assets/page-1/images/vector-oyS.png
    - assets/page-1/images/vector-AhE.png
    - assets/page-1/images/vector-mhJ.png
    - assets/page-1/images/vector-CuW.png
    - assets/page-1/images/vector-5di.png
    - assets/page-1/images/image-2-ru6.png
    - assets/page-1/images/vector-2Dn.png
    - assets/page-1/images/vector-W4Q.png
    - assets/page-1/images/image-2-X1z.png
    - assets/page-1/images/vector-xUQ.png
    - assets/page-1/images/vector-Ux8.png
    - assets/page-1/images/vector-NHW.png
    - assets/page-1/images/vector-zye.png
    - assets/page-1/images/vector-V7W.png
    - assets/page-1/images/image-2-jSx.png
    - assets/page-1/images/image-177.png
    - assets/page-1/images/image-177-XqJ.png
    - assets/page-1/images/rectangle-26.png
    - assets/page-1/images/image-175-bg.png
    - assets/page-1/images/rectangle-31.png
    - assets/page-1/images/rectangle-28.png
    - assets/page-1/images/image-175.png
    - assets/page-1/images/rectangle-32.png
    - assets/page-1/images/vector-7sn.png
    - assets/page-1/images/rectangle-27.png
    - assets/page-1/images/rectangle-30.png
    - assets/page-1/images/rectangle-29.png
    - assets/page-1/images/vector-xT2.png
    - assets/page-1/images/vector-ZSQ.png
    - assets/page-1/images/image-177-QAk.png
    - assets/page-1/images/image-175-F3v.png
    - assets/page-1/images/image-176.png
    - assets/page-1/images/rectangle-33.png
    - assets/page-1/images/vector-YiL.png
    - assets/page-1/images/vector-eUp.png
    - assets/page-1/images/vector-riL.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
